const $=id=>document.getElementById(id);
let db=null;
const status=(id,msg,isError=false)=>{const el=$(id);el.textContent=msg;el.classList.toggle("danger",isError)};
function configReady(){return window.supabase&&window.QC_SUPABASE_URL&&!window.QC_SUPABASE_URL.includes("YOUR_PROJECT")&&window.QC_SUPABASE_ANON_KEY&&!window.QC_SUPABASE_ANON_KEY.includes("YOUR_SUPABASE")}
function clearForm(){ $("question-form").reset();$("question-id").value="";$("published").checked=true;}
function values(){return {topic:$("topic").value,difficulty:$("difficulty").value,q:$("q").value.trim(),options:[0,1,2,3].map(i=>$("opt"+i).value.trim()),answer:Number($("answer").value),explanation:$("explanation").value.trim(),published:$("published").checked};}
async function loadQuestions(){const {data,error}=await db.from("questions").select("*").order("created_at",{ascending:false});if(error){status("save-status",error.message,true);return;}const host=$("question-list");if(!data.length){host.innerHTML="<p>No questions yet. Add your first one above.</p>";return;}host.innerHTML=data.map(q=>`<article class="admin-row"><strong>${escapeHtml(q.topic)} · ${escapeHtml(q.difficulty)} · ${q.published?"Published":"Draft"}</strong><p>${escapeHtml(q.q)}</p><button class="text-button" data-edit="${q.id}">Edit</button> <button class="text-button" data-toggle="${q.id}">${q.published?"Unpublish":"Publish"}</button> <button class="text-button" data-delete="${q.id}">Delete</button></article>`).join("");host.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editQuestion(data.find(q=>String(q.id)===b.dataset.edit)));host.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=async()=>{const q=data.find(q=>String(q.id)===b.dataset.toggle);const {error}=await db.from("questions").update({published:!q.published}).eq("id",q.id);status("save-status",error?error.message:"Publication status updated.",!!error);if(!error)loadQuestions()});host.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this question permanently?"))return;const {error}=await db.from("questions").delete().eq("id",b.dataset.delete);status("save-status",error?error.message:"Question deleted.",!!error);if(!error)loadQuestions()});}
function editQuestion(q){$("question-id").value=q.id;$("topic").value=q.topic;$("difficulty").value=q.difficulty;$("q").value=q.q;q.options.forEach((o,i)=>$("opt"+i).value=o);$("answer").value=String(q.answer);$("explanation").value=q.explanation;$("published").checked=q.published;window.scrollTo({top:0,behavior:"smooth"});}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
async function enterManager(){const {data:{session}}=await db.auth.getSession();if(session){$("login-panel").classList.add("hidden");$("manager").classList.remove("hidden");await loadQuestions();}}
if(!configReady()){status("login-status","Setup required: add your Supabase Project URL and publishable/anon key to config.js.",true);}
else {db=window.supabase.createClient(window.QC_SUPABASE_URL,window.QC_SUPABASE_ANON_KEY);enterManager();}
$("login").onclick=async()=>{if(!db)return;const {error}=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});status("login-status",error?error.message:"Signed in.",!!error);if(!error)enterManager();};
$("logout").onclick=async()=>{await db.auth.signOut();$("manager").classList.add("hidden");$("login-panel").classList.remove("hidden");};
$("question-form").onsubmit=async e=>{e.preventDefault();if(!db)return;const q=values();if(q.options.some(o=>!o)){status("save-status","Please fill in all four options.",true);return;}const id=$("question-id").value;const result=id?await db.from("questions").update(q).eq("id",id):await db.from("questions").insert(q);if(result.error){status("save-status",result.error.message,true);return;}status("save-status",id?"Question updated.":"Question added.");clearForm();await loadQuestions();};
$("clear-form").onclick=clearForm;
