-- QuantCrack AI Supabase setup
-- Run this entire script in Supabase Dashboard > SQL Editor > New query.
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  topic text not null check (topic in ('Arithmetic','Algebra','Geometry','Number Systems','Modern Math','Time & Work')),
  difficulty text not null check (difficulty in ('Easy','Medium','Hard')),
  q text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  answer integer not null check (answer between 0 and 3),
  explanation text not null,
  published boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.question_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.questions enable row level security;
alter table public.question_admins enable row level security;
drop policy if exists "Admins can verify own membership" on public.question_admins;
create policy "Admins can verify own membership" on public.question_admins for select to authenticated using (user_id = auth.uid());
drop policy if exists "Anyone can read published questions" on public.questions;
create policy "Anyone can read published questions" on public.questions for select using (published = true or exists (select 1 from public.question_admins a where a.user_id = auth.uid()));
drop policy if exists "Admins can insert questions" on public.questions;
create policy "Admins can insert questions" on public.questions for insert to authenticated with check (exists (select 1 from public.question_admins a where a.user_id = auth.uid()));
drop policy if exists "Admins can update questions" on public.questions;
create policy "Admins can update questions" on public.questions for update to authenticated using (exists (select 1 from public.question_admins a where a.user_id = auth.uid())) with check (exists (select 1 from public.question_admins a where a.user_id = auth.uid()));
drop policy if exists "Admins can delete questions" on public.questions;
create policy "Admins can delete questions" on public.questions for delete to authenticated using (exists (select 1 from public.question_admins a where a.user_id = auth.uid()));
-- Admin membership is not readable/writable through the public client. Add your own UUID below via SQL Editor only.
